/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 22
#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_SPACE(yycontext *yy); /* 22 */
YY_RULE(int) yy_TAB(yycontext *yy); /* 21 */
YY_RULE(int) yy_DirectiveAsciiz(yycontext *yy); /* 20 */
YY_RULE(int) yy_DirectiveData(yycontext *yy); /* 19 */
YY_RULE(int) yy_LabelBase(yycontext *yy); /* 18 */
YY_RULE(int) yy_NumberBase(yycontext *yy); /* 17 */
YY_RULE(int) yy_Register(yycontext *yy); /* 16 */
YY_RULE(int) yy_Number(yycontext *yy); /* 15 */
YY_RULE(int) yy_Address(yycontext *yy); /* 14 */
YY_RULE(int) yy_LabelMention(yycontext *yy); /* 13 */
YY_RULE(int) yy_SEP(yycontext *yy); /* 12 */
YY_RULE(int) yy_Argument(yycontext *yy); /* 11 */
YY_RULE(int) yy_Opcode(yycontext *yy); /* 10 */
YY_RULE(int) yy_AssemblerDirective(yycontext *yy); /* 9 */
YY_RULE(int) yy_Instruction(yycontext *yy); /* 8 */
YY_RULE(int) yy_LabelStart(yycontext *yy); /* 7 */
YY_RULE(int) yy_Comment(yycontext *yy); /* 6 */
YY_RULE(int) yy_WHITESPACE(yycontext *yy); /* 5 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 4 */
YY_RULE(int) yy_Line(yycontext *yy); /* 3 */
YY_RULE(int) yy_NL(yycontext *yy); /* 2 */
YY_RULE(int) yy_Program(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_DirectiveAsciiz(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DirectiveAsciiz\n"));
  {
#line 0
   handle_directive_asciiz(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_DirectiveData(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DirectiveData\n"));
  {
#line 0
   handle_directive_data(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LabelMention(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LabelMention\n"));
  {
#line 0
   handle_label_mention(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LabelStart(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LabelStart\n"));
  {
#line 0
   handle_new_label(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Number\n"));
  {
#line 0
   handle_number(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Address\n"));
  {
#line 0
   handle_address(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Register(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Register\n"));
  {
#line 0
   handle_register(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Opcode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Opcode\n"));
  {
#line 0
   handle_opcode(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Instruction(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Instruction\n"));
  {
#line 0
   handle_instruction(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_SPACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SPACE"));  if (!yymatchChar(yy, ' ')) goto l1;
  l2:;	
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TAB(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TAB"));  if (!yymatchChar(yy, '\t')) goto l4;
  l5:;	
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yymatchChar(yy, '\t')) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "TAB", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TAB", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DirectiveAsciiz(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DirectiveAsciiz"));  if (!yymatchString(yy, "asciiz")) goto l7;  if (!yy_WHITESPACE(yy)) goto l7;
  l8:;	
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;
  }  if (!yymatchChar(yy, '"')) goto l7;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l7;
#undef yytext
#undef yyleng
  }
  l10:;	
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;  if (!yymatchChar(yy, '"')) goto l12;  goto l11;
  l12:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  }
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_NL(yy)) goto l13;  goto l11;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  if (!yymatchDot(yy)) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l7;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l7;  yyDo(yy, yy_1_DirectiveAsciiz, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DirectiveAsciiz", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DirectiveAsciiz", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DirectiveData(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DirectiveData"));  if (!yymatchString(yy, "data")) goto l14;  if (!yy_WHITESPACE(yy)) goto l14;
  l15:;	
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l16;  goto l15;
  l16:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;
  }  if (!yy_NumberBase(yy)) goto l14;  yyDo(yy, yy_1_DirectiveData, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DirectiveData", yy->__buf+yy->__pos));
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DirectiveData", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LabelBase(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LabelBase"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l17;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l17;
  l18:;	
  {  int yypos19= yy->__pos, yythunkpos19= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;  goto l18;
  l19:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l17;
#undef yytext
#undef yyleng
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "LabelBase", yy->__buf+yy->__pos));
  return 1;
  l17:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LabelBase", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NumberBase(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NumberBase"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l20;
#undef yytext
#undef yyleng
  }
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yymatchString(yy, "0b")) goto l22;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l22;
  l23:;	
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;  goto l23;
  l24:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  }  goto l21;
  l22:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  if (!yymatchString(yy, "0x")) goto l25;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l25;
  l26:;	
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;
  }  goto l21;
  l25:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l20;
  l28:;	
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l29;  goto l28;
  l29:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }
  }
  l21:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l20;
#undef yytext
#undef yyleng
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "NumberBase", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NumberBase", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Register(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Register"));  if (!yymatchChar(yy, '%')) goto l30;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l30;
#undef yytext
#undef yyleng
  }
  {  int yypos31= yy->__pos, yythunkpos31= yy->__thunkpos;  if (!yymatchString(yy, "ba")) goto l32;  goto l31;
  l32:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchString(yy, "dc")) goto l33;  goto l31;
  l33:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchString(yy, "sp")) goto l34;  goto l31;
  l34:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchString(yy, "pc")) goto l35;  goto l31;
  l35:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, 'a')) goto l36;  goto l31;
  l36:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, 'b')) goto l37;  goto l31;
  l37:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, 'c')) goto l38;  goto l31;
  l38:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, 'd')) goto l30;
  }
  l31:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l30;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Register, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Register", yy->__buf+yy->__pos));
  return 1;
  l30:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Register", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Number"));  if (!yy_NumberBase(yy)) goto l39;  yyDo(yy, yy_1_Number, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Address"));  if (!yymatchChar(yy, '[')) goto l40;  if (!yy_NumberBase(yy)) goto l40;  if (!yymatchChar(yy, ']')) goto l40;  yyDo(yy, yy_1_Address, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Address", yy->__buf+yy->__pos));
  return 1;
  l40:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LabelMention(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LabelMention"));  if (!yymatchChar(yy, '.')) goto l41;  if (!yy_LabelBase(yy)) goto l41;  yyDo(yy, yy_1_LabelMention, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LabelMention", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LabelMention", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SEP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SEP"));  if (!yymatchChar(yy, ',')) goto l42;
  l43:;	
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l44;  goto l43;
  l44:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SEP", yy->__buf+yy->__pos));
  return 1;
  l42:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Argument(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Argument"));
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yy_LabelMention(yy)) goto l47;  goto l46;
  l47:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Address(yy)) goto l48;  goto l46;
  l48:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Number(yy)) goto l49;  goto l46;
  l49:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Register(yy)) goto l45;
  }
  l46:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Argument", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Argument", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Opcode(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Opcode"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l50;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;
  l51:;	
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l52;  goto l51;
  l52:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l50;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Opcode, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Opcode", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Opcode", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_AssemblerDirective(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "AssemblerDirective"));  if (!yymatchChar(yy, '#')) goto l53;
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yy_DirectiveData(yy)) goto l55;  goto l54;
  l55:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;  if (!yy_DirectiveAsciiz(yy)) goto l53;
  }
  l54:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AssemblerDirective", yy->__buf+yy->__pos));
  return 1;
  l53:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AssemblerDirective", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Instruction(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Instruction"));
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;  if (!yy_Opcode(yy)) goto l58;  if (!yy_WHITESPACE(yy)) goto l58;
  l59:;	
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l60;  goto l59;
  l60:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;
  }  if (!yy_Argument(yy)) goto l58;
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;  if (!yy_SEP(yy)) goto l63;  goto l64;
  l63:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;
  }
  l64:;	
  l61:;	
  {  int yypos62= yy->__pos, yythunkpos62= yy->__thunkpos;  if (!yy_Argument(yy)) goto l62;
  {  int yypos65= yy->__pos, yythunkpos65= yy->__thunkpos;  if (!yy_SEP(yy)) goto l65;  goto l66;
  l65:;	  yy->__pos= yypos65; yy->__thunkpos= yythunkpos65;
  }
  l66:;	  goto l61;
  l62:;	  yy->__pos= yypos62; yy->__thunkpos= yythunkpos62;
  }  goto l57;
  l58:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yy_Opcode(yy)) goto l56;
  }
  l57:;	  yyDo(yy, yy_1_Instruction, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Instruction", yy->__buf+yy->__pos));
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Instruction", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LabelStart(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LabelStart"));  if (!yy_LabelBase(yy)) goto l67;  if (!yymatchChar(yy, ':')) goto l67;  yyDo(yy, yy_1_LabelStart, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LabelStart", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LabelStart", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Comment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Comment"));  if (!yymatchChar(yy, ';')) goto l68;
  l69:;	
  {  int yypos70= yy->__pos, yythunkpos70= yy->__thunkpos;
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yy_NL(yy)) goto l71;  goto l70;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }  if (!yymatchDot(yy)) goto l70;  goto l69;
  l70:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;
  }  if (!yy_NL(yy)) goto l68;
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 1;
  l68:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_WHITESPACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "WHITESPACE"));
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yy_TAB(yy)) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yy_SPACE(yy)) goto l72;
  }
  l73:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "WHITESPACE", yy->__buf+yy->__pos));
  return 1;
  l72:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHITESPACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yymatchDot(yy)) goto l76;  goto l75;
  l76:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Line"));
  {  int yypos78= yy->__pos, yythunkpos78= yy->__thunkpos;
  l80:;	
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l81;  goto l80;
  l81:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;
  }  if (!yy_Comment(yy)) goto l79;  goto l78;
  l79:;	  yy->__pos= yypos78; yy->__thunkpos= yythunkpos78;
  l82:;	
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }
  {  int yypos84= yy->__pos, yythunkpos84= yy->__thunkpos;  if (!yy_LabelStart(yy)) goto l85;
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;
  l88:;	
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l89;  goto l88;
  l89:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;
  }
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yy_Instruction(yy)) goto l91;  goto l90;
  l91:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yy_AssemblerDirective(yy)) goto l86;
  }
  l90:;	  goto l87;
  l86:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  }
  l87:;	  goto l84;
  l85:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;  if (!yy_Instruction(yy)) goto l92;  goto l84;
  l92:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;  if (!yy_AssemblerDirective(yy)) goto l77;
  }
  l84:;	
  {  int yypos93= yy->__pos, yythunkpos93= yy->__thunkpos;
  l95:;	
  {  int yypos96= yy->__pos, yythunkpos96= yy->__thunkpos;  if (!yy_WHITESPACE(yy)) goto l96;  goto l95;
  l96:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;
  }  if (!yy_Comment(yy)) goto l93;  goto l94;
  l93:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;
  }
  l94:;	
  }
  l78:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 1;
  l77:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NL"));
  {  int yypos98= yy->__pos, yythunkpos98= yy->__thunkpos;  if (!yymatchString(yy, "\r\n")) goto l99;  goto l98;
  l99:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;  if (!yymatchChar(yy, '\r')) goto l100;  goto l98;
  l100:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;  if (!yymatchChar(yy, '\n')) goto l97;
  }
  l98:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NL", yy->__buf+yy->__pos));
  return 1;
  l97:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Program(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Program"));
  l104:;	
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yy_NL(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;
  }  if (!yy_Line(yy)) goto l101;
  l106:;	
  {  int yypos107= yy->__pos, yythunkpos107= yy->__thunkpos;  if (!yy_NL(yy)) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos107; yy->__thunkpos= yythunkpos107;
  }
  l102:;	
  {  int yypos103= yy->__pos, yythunkpos103= yy->__thunkpos;
  l108:;	
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yy_NL(yy)) goto l109;  goto l108;
  l109:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;
  }  if (!yy_Line(yy)) goto l103;
  l110:;	
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;  if (!yy_NL(yy)) goto l111;  goto l110;
  l111:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;
  }  goto l102;
  l103:;	  yy->__pos= yypos103; yy->__thunkpos= yythunkpos103;
  }  if (!yy_EOF(yy)) goto l101;
  yyprintf((stderr, "  ok   %s @ %s\n", "Program", yy->__buf+yy->__pos));
  return 1;
  l101:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Program", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Program);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
